version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    expose:
      - "5672"
    ports:
      - "15672:15672"
  nameko: &nameko
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - pipenv
      - run
      - start_nameko
      - helloworld
    volumes:
      - ./:/usr/src/app:rw
    links:
      - rabbitmq
  shell:
    <<: *nameko
    command:
      - pipenv
      - run
      - shell_nameko
