version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    expose:
      - "5672"
    ports:
      - "15672:15672"
  nameko: &nameko
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - nameko
      - run
      - --config
      - ./config/nameko-config.yaml
      - helloworld
    volumes:
      - ./:/usr/src/app:rw
  shell:
    <<: *nameko
    command:
      - nameko
      - shell
      - --config
      - ./config/nameko-config.yaml
